<a href="https://colab.research.google.com/github/NDsasuke/Autocorrelation-function-Diagnostics-and-prediction/blob/main/Diagnostics%20and%20prediction/Model%20Evaluation%20Metrics/Evaluation_Metrics_for_Multi_Class_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



1. **Importing Libraries and Loading the Dataset:**
   - This segment imports the necessary libraries and modules for our code.
   - It imports `numpy` for numerical computations, `load_digits` from `sklearn.datasets` to load the Digits dataset, `train_test_split` from `sklearn.model_selection` to split the dataset into training and test sets, `LogisticRegression` from `sklearn.linear_model` to train a logistic regression model, and various evaluation metrics from `sklearn.metrics`.
   - It also loads the Digits dataset using `load_digits()` function and assigns the features to `X` and the target variable to `y`.


In [2]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

In [3]:
# Load the Digits dataset
data = load_digits()
X = data.data
y = data.target


2. **Splitting the Data into Train and Test Sets:**
   - This segment splits the loaded dataset into training and test sets using the `train_test_split` function.
   - It assigns 80% of the data to the training set (`X_train` and `y_train`) and 20% to the test set (`X_test` and `y_test`).
   - The `test_size` parameter is set to 0.2, indicating that we want 20% of the data for testing.


In [4]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


3. **Training the Logistic Regression Model and Making Predictions:**
   - This segment creates an instance of the logistic regression model using `LogisticRegression()` and trains it on the training data using the `fit` method.
   - Once the model is trained, it makes predictions on the test set using the `predict` method and assigns the predicted labels to `y_pred`.


In [5]:
# Train a logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [6]:
# Make predictions on the test set
y_pred = model.predict(X_test)


4. **Computing Evaluation Metrics:**
   - This segment computes various evaluation metrics suitable for multi-class classification problems.
   - It calculates the confusion matrix using the `confusion_matrix` function, passing the true labels (`y_test`) and the predicted labels (`y_pred`).
   - The macro-averaged precision is computed using `precision_score` with the `average` parameter set to `'macro'`. It calculates the precision for each class and then takes the average.
   - The macro-averaged recall is calculated using `recall_score` with the `average` parameter set to `'macro'`. It computes the recall for each class and then takes the average.
   - The macro-averaged F1 score is computed using `f1_score` with the `average` parameter set to `'macro'`. It calculates the F1 score for each class and then takes the average.


In [7]:
# Compute evaluation metrics
conf_matrix = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')


5. **Printing the Evaluation Metrics:**
   - This segment prints the computed evaluation metrics to the console.
   - It first displays the confusion matrix using `print("Confusion Matrix:")` and `print(conf_matrix)`.
   - Then it prints the macro-averaged precision, macro-averaged recall, and macro-averaged F1 score using `print("Macro-Averaged Precision:", precision)`, `print("Macro-Averaged Recall:", recall)`, and `print("Macro-Averaged F1 Score:", f1)`.

By executing this code, you will obtain the evaluation metrics for your multi-class classification model, allowing you to assess its performance in terms of macro-averaged precision, macro-averaged recall, and macro-averaged F1 score. The confusion matrix provides a detailed breakdown of the predictions for each class.

In [8]:
# Print the evaluation metrics
print("Confusion Matrix:")
print(conf_matrix)
print("Macro-Averaged Precision:", precision)
print("Macro-Averaged Recall:", recall)
print("Macro-Averaged F1 Score:", f1)


Confusion Matrix:
[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  1  0  0 44  0  1  0  0  0]
 [ 0  0  1  0  0 44  1  0  0  1]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  1  0 33  0  0]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  0  0  0  0  1 38]]
Macro-Averaged Precision: 0.9708830464104297
Macro-Averaged Recall: 0.9721963660579865
Macro-Averaged F1 Score: 0.9713725658623401
